### ISSUE TITLE
KeyError: 'labels'

### ISSUE THREAD

**Issue by EvanSong77** [NLPWM-WHU/SLGM#1]
28%|███████████                             | 312/1130 [01:35<04:02,  3.38it/s]Traceback (most recent call last):
  File "/home/codewen/.pycharm_helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/codewen/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/codewen/codewen_workspace/SLGM/run.py", line 329, in <module>
    main()
  File "/home/codewen/codewen_workspace/SLGM/run.py", line 274, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/codewen/anaconda3/envs/SLGM_env/lib/python3.9/site-packages/transformers/trainer.py", line 1332, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/codewen/anaconda3/envs/SLGM_env/lib/python3.9/site-packages/transformers/trainer.py", line 1883, in training_step
python-BaseException    inputs = self._prepare_inputs(inputs)
  File "/home/codewen/codewen_workspace/SLGM/marker_trainer.py", line 129, in _prepare_inputs
    inputs = self.ignore_pad_token_for_training(inputs)
  File "/home/codewen/codewen_workspace/SLGM/marker_trainer.py", line 135, in ignore_pad_token_for_training
    lm_labels = inputs['ao_data']['labels']
KeyError: 'labels'

![image](https://github.com/NLPWM-WHU/SLGM/assets/48975863/6db62cdb-2409-4295-8158-569d53f384f6)
代码是否有问题？

**Comment by ZHOUSHEN713** [comment]
您好，我重新下载了代码，并创建了一个新的环境，按照Readme中的步骤可以正常运行，并没有出现您的问题。我认为您的问题可能是由于环境差异导致的。下面是新创建环境的包列表：
<img width="449" alt="image" src="https://github.com/NLPWM-WHU/SLGM/assets/49969011/f8891557-7b4f-42e7-8028-032930ed909a">
运行结果
<img width="809" alt="image" src="https://github.com/NLPWM-WHU/SLGM/assets/49969011/c1418284-5664-444f-aab8-8867781dbd5b">
